name: Publish to PyPI

on:
  push:
    tags:
      - '*'

jobs:
  build-and-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Upgrade pip and install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel
    - name: Extract tag name
      id: tag
      run: echo "PACKAGE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    - name: Check PACKAGE_VERSION
      run: |
        if [ -z "$PACKAGE_VERSION" ]; then
          echo "Error: PACKAGE_VERSION is not set. Exiting."
          exit 1
        fi
    - name: Build a binary wheel
      env:
        PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
      run: python setup.py sdist bdist_wheel
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
